apiVersion: apps/v1
kind: Deployment
metadata:
  name: ok-deployment
  namespace: pco
  labels:
    app: ok
spec:
  selector:
    matchLabels:
      app: ok
  template:
    metadata:
      labels:
        app: ok
    spec:
      containers:
      - name: ok
        image: docker.io/rlkamradt/hellok8s:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ok-service
  namespace: pco
spec:
  type: ClusterIP
  selector:
    app: ok
  ports:
  - port: 8080
    targetPort: 8080
